
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
server.port=7072

# Allow circular references temporarily to resolve startup issue
#spring.main.allow-circular-references=true

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/department_db_1?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=knnp2001

#jpa vendor adapter configuration

#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.boot.message= i am from department updated


